rootLogger.level = INFO
rootLogger.appenderRef.console.ref = ConsoleAppender

logger.velocity.name = in.gov.uidai.dp.velocity.engine
logger.velocity.level = INFO

logger.flink.name = org.apache.flink
logger.flink.level = WARN

logger.kafka.name = org.apache.kafka
logger.kafka.level = WARN

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = WARN

logger.iceberg.name = org.apache.iceberg
logger.iceberg.level = WARN

appender.console.name = ConsoleAppender
appender.console.type = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} [%t] %-5p %-40c{1.} - %m%n
